#!/usr/bin/env python3
"""Generate the hanzi subset list for the tiny-cjk flash font variant.

Emits cjk_subset.txt: one hanzi per line, sorted by codepoint, derived from
the GB2312-80 character set via Python's built-in gb2312 codec. GB2312 was
frequency-selected for exactly this purpose (common simplified Chinese):

  Level 1 (rows 0xB0-0xD7): 3755 most common hanzi, pinyin-sorted.
  Level 2 (rows 0xD8-0xF7): 3008 additional hanzi, radical-sorted.

Both levels together cover essentially all modern simplified prose. Kana,
CJK punctuation, and fullwidth forms are added as whole-block intervals in
build-cjk-flash-font.sh, not here.

The output is deterministic (codec tables are frozen), so the committed
cjk_subset.txt can always be regenerated bit-identically.

Usage:
  python3 gen_cjk_subset.py [--level1-only] [-o cjk_subset.txt]
"""

import argparse

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--level1-only", action="store_true",
                    help="Emit only GB2312 level 1 (3755 hanzi) instead of levels 1+2 (6763).")
parser.add_argument("-o", "--output", default="cjk_subset.txt", help="Output file path.")
args = parser.parse_args()

last_row = 0xD7 if args.level1_only else 0xF7

codepoints = set()
for hi in range(0xB0, last_row + 1):
    for lo in range(0xA1, 0xFF):
        try:
            ch = bytes([hi, lo]).decode("gb2312")
        except UnicodeDecodeError:
            continue
        codepoints.add(ord(ch))

# U+3007 IDEOGRAPHIC NUMBER ZERO lives in the GB2312 symbol area, not the
# hanzi rows, but is required for dates ("二〇二六年"). The punctuation block
# interval 0x3000-0x303F added by the build script covers it; keep this note
# here so a future narrowing of that interval doesn't silently drop it.

with open(args.output, "w", encoding="utf-8") as f:
    f.write("# Generated by gen_cjk_subset.py -- do not edit by hand.\n")
    f.write(f"# GB2312 level {'1' if args.level1_only else '1+2'} hanzi, "
            f"{len(codepoints)} codepoints, sorted by codepoint.\n")
    for cp in sorted(codepoints):
        f.write(chr(cp) + "\n")

print(f"{args.output}: {len(codepoints)} hanzi")
