#!/usr/bin/env python3
"""Generate the hanzi subset list for the tiny-cjk flash font variant.

Emits cjk_subset.txt: one hanzi per line, sorted by codepoint, derived from
the GB2312-80 character set via Python's built-in gb2312 codec. GB2312 was
frequency-selected for exactly this purpose (common simplified Chinese):

  Level 1 (rows 0xB0-0xD7): 3755 most common hanzi, pinyin-sorted.
  Level 2 (rows 0xD8-0xF7): 3008 additional hanzi, radical-sorted.

Both levels together cover essentially all modern simplified prose. Kana,
CJK punctuation, and fullwidth forms are added as whole-block intervals in
build-cjk-flash-font.sh, not here.

The output is deterministic (codec tables are frozen), so the committed
cjk_subset.txt can always be regenerated bit-identically.

Usage:
  python3 gen_cjk_subset.py [--level1-only] [-o cjk_subset.txt]
"""

import argparse

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--level1-only", action="store_true",
                    help="Emit only GB2312 level 1 (3755 hanzi) instead of levels 1+2 (6763).")
parser.add_argument("--traditional", action="store_true",
                    help="Also include Big5 level 1 (frequently used traditional hanzi). "
                         "Adds ~2083 glyphs over GB2312 alone; 3328 more are already shared.")
parser.add_argument("-o", "--output", default="cjk_subset.txt", help="Output file path.")
args = parser.parse_args()

last_row = 0xD7 if args.level1_only else 0xF7

codepoints = set()
for hi in range(0xB0, last_row + 1):
    for lo in range(0xA1, 0xFF):
        try:
            ch = bytes([hi, lo]).decode("gb2312")
        except UnicodeDecodeError:
            continue
        codepoints.add(ord(ch))

gb2312_count = len(codepoints)

# Traditional Chinese, via Big5 level 1 (lead bytes 0xA1-0xC6): the frequently
# used set, the Big5 analogue of GB2312 level 1+2. Level 2 (0xC7-0xF9) is the
# rare/historical tail -- 6595 further glyphs, roughly 1.1 MB, which does not
# fit the flash slot.
#
# The two sets overlap heavily: 3328 of Big5 level 1's 5411 characters are
# shapes Simplified and Traditional share and are already present from GB2312,
# so the union costs only ~2083 new glyphs.
#
# No setting selects between them. The baked face is a codepoint-keyed
# fallback, so a Traditional book asks for U+5B78 and a Simplified one asks
# for U+5B66; both resolve from the same face, including within one book.
if args.traditional:
    for hi in range(0xA1, 0xC7):
        for lo in list(range(0x40, 0x7F)) + list(range(0xA1, 0xFF)):
            try:
                ch = bytes([hi, lo]).decode("big5")
            except UnicodeDecodeError:
                continue
            # Han only: the Big5 symbol/kana rows would duplicate the whole-block
            # intervals the build script already adds.
            if 0x4E00 <= ord(ch) <= 0x9FFF:
                codepoints.add(ord(ch))

# U+3007 IDEOGRAPHIC NUMBER ZERO lives in the GB2312 symbol area, not the
# hanzi rows, but is required for dates ("二〇二六年"). The punctuation block
# interval 0x3000-0x303F added by the build script covers it; keep this note
# here so a future narrowing of that interval doesn't silently drop it.

with open(args.output, "w", encoding="utf-8") as f:
    f.write("# Generated by gen_cjk_subset.py -- do not edit by hand.\n")
    scope = f"GB2312 level {'1' if args.level1_only else '1+2'}"
    if args.traditional:
        scope += " + Big5 level 1"
    f.write(f"# {scope} hanzi, {len(codepoints)} codepoints, sorted by codepoint.\n")
    for cp in sorted(codepoints):
        f.write(chr(cp) + "\n")

extra = len(codepoints) - gb2312_count
print(f"{args.output}: {len(codepoints)} hanzi"
      + (f" ({gb2312_count} simplified + {extra} traditional-only)" if args.traditional else ""))
