"""Bake the crumble-prebake WASM artifacts into PROGMEM headers.

Companion to build_html.py: that script walks src/ for .html and .js;
this one consumes the build artifacts the prebake CLI emits to
tools/crumble-prebake/build-wasm/ and produces a parallel header that
the device's web server can serve at /js/crumble-prebake.js and
/wasm/crumble-prebake.wasm.

Inputs (must exist before this runs):
  tools/crumble-prebake/build-wasm/crumble-prebake.js   (~170 KB JS glue)
  tools/crumble-prebake/build-wasm/crumble-prebake.wasm (~1.6 MB)

Outputs (overwritten each run):
  src/network/html/wasm/crumblePrebakeJs.generated.h
  src/network/html/wasm/crumblePrebakeWasm.generated.h

Both outputs are gzip-compressed (Content-Encoding: gzip on serve, just
like the HTML/JS path). The wasm gzips from 1.6 MB to ~850 KB and the
JS glue from 170 KB to ~46 KB. Total extra flash ~900 KB, well inside
the 7.5 MB per-OTA-slot partition table.

If the build artifacts don't exist, this script emits empty placeholder
headers so the device firmware build doesn't fail when the WASM isn't
yet built. Optimizer.js gracefully falls back to the old per-image
bake-pxc flow if the prebake module can't be loaded (added in step
28.5). To produce a firmware with the WASM baked in, run:

  tools/crumble-prebake/build-wasm.sh
  pio run -e crosspoint_x4

in that order. This script runs as a PlatformIO pre-step, so a fresh
PIO build picks up the latest WASM automatically.
"""

import gzip
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WASM_BUILD_DIR = os.path.join(REPO_ROOT, "tools", "crumble-prebake", "build-wasm")
OUT_DIR = os.path.join(REPO_ROOT, "src", "network", "html", "wasm")

ASSETS = [
    {
        "src": os.path.join(WASM_BUILD_DIR, "crumble-prebake.js"),
        "ident": "crumblePrebakeJs",
        "header": "crumblePrebakeJs.generated.h",
    },
    {
        "src": os.path.join(WASM_BUILD_DIR, "crumble-prebake.wasm"),
        "ident": "crumblePrebakeWasm",
        "header": "crumblePrebakeWasm.generated.h",
    },
]


def emit_header(out_path: str, ident: str, payload: bytes, original_size: int) -> None:
    """Write a PROGMEM byte-array header matching the build_html.py layout."""
    with open(out_path, "w", encoding="utf-8") as h:
        h.write("// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
        h.write("#pragma once\n")
        h.write("#include <cstddef>\n\n")
        h.write(f"constexpr char {ident}[] PROGMEM = {{\n")
        # Empty payload means "asset not built". We still emit a valid array
        # (`{0}`) so the constant is well-formed; CompressedSize is 0 so the
        # serve handler can detect-and-fallback.
        if payload:
            for i in range(0, len(payload), 16):
                chunk = payload[i : i + 16]
                hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
                h.write(f"  {hex_values},\n")
        else:
            h.write("  0,\n")
        h.write("};\n\n")
        h.write(f"constexpr size_t {ident}CompressedSize = {len(payload)};\n")
        h.write(f"constexpr size_t {ident}OriginalSize = {original_size};\n")


def main() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    total_compressed = 0
    total_original = 0
    missing = []

    for asset in ASSETS:
        src = asset["src"]
        ident = asset["ident"]
        out_path = os.path.join(OUT_DIR, asset["header"])

        if not os.path.exists(src):
            # Emit empty placeholder so the firmware still compiles. Optimizer
            # falls back when the runtime sees CompressedSize == 0.
            emit_header(out_path, ident, b"", 0)
            missing.append(src)
            print(f"[wasm-assets] {ident}: MISSING ({src}) -- emitted empty placeholder")
            continue

        with open(src, "rb") as f:
            raw = f.read()
        compressed = gzip.compress(raw, compresslevel=9)
        emit_header(out_path, ident, compressed, len(raw))
        total_compressed += len(compressed)
        total_original += len(raw)
        print(
            f"[wasm-assets] {ident}: {len(raw)} -> {len(compressed)} bytes "
            f"({100 * len(compressed) / max(1, len(raw)):.1f}% gzipped)"
        )

    if missing:
        print(
            f"[wasm-assets] note: {len(missing)} asset(s) missing. To bake the WASM "
            f"into firmware, run tools/crumble-prebake/build-wasm.sh first.",
            file=sys.stderr,
        )

    print(
        f"[wasm-assets] total: {total_original} -> {total_compressed} bytes "
        f"(~{total_compressed / 1024:.0f} KB into flash)"
    )
    return 0


# PlatformIO pre-script entry: extra_scripts loads this module and runs main()
# at the start of every build. The wrapper guards against env-less import (so
# the script also works when invoked directly via `python build_wasm_assets.py`).
try:
    Import("env")  # type: ignore[name-defined]
    main()
except (NameError, Exception):  # noqa: BLE001
    if __name__ == "__main__":
        sys.exit(main())
