"""
Embed the WASM-built crumble-prebake.{js,wasm} into PROGMEM headers so
the device's web server can serve them at /js/crumble-prebake.{js,wasm}
without needing the file system.

build_html.py only walks src/ and only handles UTF-8 text (it would
choke on the wasm binary). This script targets the specific pair of
output files from tools/crumble-prebake/build-wasm/.

Outputs:
  src/network/html/wasm/CrumblePrebakeJs.generated.h
  src/network/html/wasm/CrumblePrebakeWasm.generated.h

Each header exposes a PROGMEM byte array + its gzip-compressed size,
in the same shape as build_html.py's output so the same sendBufferGzip
serving path works unchanged.
"""

import gzip
import os
from pathlib import Path

# PlatformIO runs extra_scripts from the project root, and SCons doesn't
# expose __file__ -- use cwd-relative paths to match other build scripts
# (build_html.py, gen_i18n.py).
WASM_DIR = Path("tools/crumble-prebake/build-wasm")
OUT_DIR = Path("src/network/html/wasm")

TARGETS = [
    ("crumble-prebake.js", "CrumblePrebakeJs"),
    ("crumble-prebake.wasm", "CrumblePrebakeWasm"),
]


def embed(src_path: Path, identifier: str) -> None:
    # CRUMBLE_OMIT_WASM=1 forces stub generation even when the WASM is
    # built. Used for release builds where we want the firmware binary
    # to stay small enough to leave OTA headroom; the device-side
    # /js/crumble-prebake.* handlers fall through to a 404 and the web
    # optimizer falls back to its CDN-loaded variant.
    if os.environ.get("CRUMBLE_OMIT_WASM") == "1":
        print(f"[embed_wasm] skip {src_path.name}: CRUMBLE_OMIT_WASM=1")
        compressed = b""
        original_size = 0
    elif not src_path.exists():
        # The WASM build is optional -- if the developer hasn't run
        # tools/crumble-prebake/build-wash.sh, emit a tiny stub header
        # so the firmware still compiles. The /js/crumble-prebake.*
        # handlers will return 404 at runtime via a zero-length check.
        print(f"[embed_wasm] skip {src_path.name}: not built yet")
        compressed = b""
        original_size = 0
    else:
        original = src_path.read_bytes()
        original_size = len(original)
        compressed = gzip.compress(original, compresslevel=9)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    header_path = OUT_DIR / f"{identifier}.generated.h"
    with header_path.open("w", encoding="utf-8") as h:
        h.write("// THIS FILE IS AUTOGENERATED BY scripts/embed_wasm.py, DO NOT EDIT\n\n")
        h.write("#pragma once\n")
        h.write("#include <cstddef>\n\n")
        h.write(f"constexpr char {identifier}[] PROGMEM = {{\n")
        for i in range(0, len(compressed), 16):
            chunk = compressed[i:i + 16]
            hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
            h.write(f"  {hex_values},\n")
        if not compressed:
            h.write("  0x00,\n")  # empty array would not compile
        h.write("};\n\n")
        h.write(f"constexpr size_t {identifier}CompressedSize = {len(compressed)};\n")
        h.write(f"constexpr size_t {identifier}OriginalSize = {original_size};\n")
    pct = (100 * len(compressed) / original_size) if original_size else 0
    print(f"[embed_wasm] {src_path.name} -> {identifier}.generated.h "
          f"({original_size} B -> {len(compressed)} B gz, {pct:.1f}%)")


# PlatformIO calls extra_scripts as `python <script>.py` with `Import("env")`
# in scope. We don't actually need env (no command-line build manipulation),
# but we DO need to be importable and side-effect-free at module level.
def main() -> None:
    for filename, identifier in TARGETS:
        embed(WASM_DIR / filename, identifier)


if __name__ == "__main__":
    main()
else:
    # Called as a PlatformIO pre-script. Run during import.
    main()
